repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 6306a48f7dae5861702d573c9c247e4e9498e867 # pragma: allowlist secret
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    files: \.sh
  - id: check-json
  - id: check-vcs-permalinks
  - id: check-yaml
    exclude: ^helm
  - id: check-ast
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: fc260393cc4ec09f8fc0a5ba4437f481c8b55dc1 # pragma: allowlist secret
  hooks:
  - id: prettier
    exclude: (\.yaml|\.yml)
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 628f6aeaeb488ae497b918ceda9cc2b0eaa02079 # pragma: allowlist secret
  hooks:
  - id: pretty-format-yaml
    exclude: ^helm
    args: [--autofix, --indent, '2']
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 95fc56f84c6c0d2363c47dfec6c6e931d26e9f36 # pragma: allowlist secret
  hooks:
  - id: terraform_fmt
  # - id: terraform_validate
  - id: terraform_docs
  - id: terraform_tflint
- repo: https://github.com/Yelp/detect-secrets
  rev: 44095a02ebcdd4d3d84b11b92d986d7a05d88058 # pragma: allowlist secret
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
    exclude: package.lock.json
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: 3f77b826548d8dc2d26675f077361c92773b50a7 # pragma: allowlist secret
  hooks:
  - id: shellcheck

exclude: ^(CHANGELOG\.md).*$
