apiVersion: batch/v1
kind: Job
metadata:
  name: clamav-load-tests
spec:
  template:
    spec:
      containers:
      - name: clamav-load-tests
        image: ghcr.io/bcgov/clamav-load-testing:main
        imagePullPolicy: Always
        env:
        - name: CLAMAV_HOST
          value: clamav.b5395d-dev.svc.cluster.local
        - name: CLAMAV_PORT
          value: '3310'
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 400Mi
      restartPolicy: Never
